version: "3"

services:
  #CLIENT
  scorpio-client:
    container_name: scorpio-client
    image: scorpio-client-react-i
    build:
      context: ../client
    ports:
      - 6080:80
    networks:
      - scorpio-net

  #SERVER
  scorpio-server:
    container_name: scorpio-server
    image: nginx:stable-alpine
    restart: always # always restart unless stopped manually
    ports:
      - 6082:80
    volumes:
      - ../server:/var/www/html
      - ./server/nginx/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - scorpio-net

  #API
  scorpio-api:
    container_name: scorpio-api
    image: denoldtimer/api:1.0
    build:
      context: .
      dockerfile: ./server/php/Dockerfile
    restart: always # always restart unless stopped manually
    volumes:
      - ../server:/var/www/html
      - ./server/php/custom.ini:/usr/local/etc/php/conf.d/custom.ini
    depends_on:
      - scorpio-db
    networks:
      - scorpio-net

  #DATABASE
  scorpio-db:
    container_name: scorpio-db
    platform: linux/x86_64
    image: mysql:8
    ports:
      - 6086:3306
    command: --init-file /data/application/init.sql
    volumes:
      - ./server/mysql/init.sql:/data/application/init.sql
      - scorpio-data:/var/lib/mysql
    restart: always # always restart unless stopped manually
    environment:
      MYSQL_DATABASE: scorpio
      MYSQL_ROOT_PASSWORD: r00tadmin
    networks:
      - scorpio-net

  #ADMIN
  scorpio-admin:
    container_name: scorpio-admin
    image: phpmyadmin/phpmyadmin
    environment:
      PMA_HOST: scorpio-db
      PMA_PORT: 3306
      PMA_ARBITRARY: 1
    ports:
      - 6084:80
    networks:
      - scorpio-net

#VOLUMES
volumes:
  scorpio-data:
    driver: local
    name: scorpio-data

#NETWORKS
networks:
  scorpio-net:
    name: scorpio-net
